app/views/outputs.py
from flask import Blueprint, render_template
from ..models.waterbodies import *
from ..utils.html_utils import dataframe_to_html_table
from ..Connections import db_archive, db_variables, fs_server
from ..utils import data_utils as du
import pandas

outputs = Blueprint('outputs', __name__)

# Route to outputs page
@outputs.route('/outputs/', methods=['GET'])
@outputs.route('/outputs/<unique_id>')
def outputs_route(unique_id=None):

    archive_connection = db_archive.DB_ARCHIVE()

    # Check if Archive is empty, in which case show Error HTML page
    if archive_connection.get_most_recent_id() == 0:
        return render_template('archive-empty.html', active_page='outputs')
    # Check if UniqueID provided or Exists, if not then show last calculation
    elif unique_id == None or archive_connection.check_id_exists(unique_id=unique_id) == None:
        return create_outputs_page(unique_id=archive_connection.get_most_recent_id())
    # Show page for the UniqueID provided (UniqueID exists)
    else:
        return create_outputs_page(unique_id=unique_id)



def create_outputs_page(unique_id):

    archive_connection = db_archive.DB_ARCHIVE()
    variables_connection = db_variables.DB_VARIABLES()
    fs_server_connection = fs_server.FS_SERVER()

    try:
        output_values = archive_connection.get_all_output_page_values(unique_id=unique_id)
        fs_server_connection.get_graph(folder_name='BOD_GRAPH', file_name=unique_id)
        fs_server_connection.get_graph(folder_name='NH3_GRAPH', file_name=unique_id)

        output_page_values = {
            "river_stretch_name": output_values['river_stretch_name'],
            "cso_input_data" : variables_connection.retrieve_cso_inputs(unique_id),
            "post_spill_bod_ninetynine_percentile": output_values['bod_post_spill'],
            "post_spill_nh3_ninetynine_percentile": output_values['nh3_post_spill'],
            "pre_spill_bod_ninetynine_percentile": output_values['bod_pre_spill'],
            "pre_spill_nh3_ninetynine_percentile": output_values['nh3_pre_spill'],
            "river_class": output_values['water_body_type'],
            "pre_spill_bod_wfd_std_attained": output_values['bod_wfd_standard_pre_spill'],
            "post_spill_bod_wfd_std_attained": output_values['bod_wfd_standard_post_spill'],
            "in_class_bod_percentage_deteriotation" : output_values['bod_in_class_deterioration'],
            "bod_score" : output_values['bod_soaf_score'],
            "pre_spill_nh3_wfd_std_attained": output_values['nh3_wfd_standard_pre_spill'],
            "post_spill_nh3_wfd_std_attained": output_values['nh3_wfd_standard_post_spill'],
            "in_class_nh3_percentage_deteriotation" : output_values['nh3_in_class_deterioration'],
            "nh3_score": output_values['nh3_soaf_score'],
            "name_of_sim" : output_values['name_of_sim'],
            "input_data":  variables_connection.retrieve_inputs(unique_id),
            "nh3_soaf_class": du.calculate_soaf_impact_class(output_values['nh3_soaf_score']),
            "bod_soaf_class":  du.calculate_soaf_impact_class(output_values['bod_soaf_score'])
        }
        bod_graph = 'graph_templates/BOD_GRAPH/' + unique_id + '.html'
        nh3_graph = 'graph_templates/NH3_GRAPH/' + unique_id + '.html'

        dataframe = fs_server_connection.get_csv(folder_name='OUTPUT', file_name=unique_id)
        dataframe = pandas.read_csv(dataframe)
        fs_server_connection.delete_local_file(folder_name='OUTPUT', file_name=unique_id)

        return render_template('outputs.html', output_page_values=output_page_values, bod_graph=bod_graph, nh3_graph=nh3_graph, tables=dataframe_to_html_table(dataframe)) 

    finally:
        fs_server_connection.delete_local_graph(folder_name='BOD_GRAPH', file_name=unique_id)
        fs_server_connection.delete_local_graph(folder_name='NH3_GRAPH', file_name=unique_id)

app/templates/includes/_aeration-card.html
<div class="card aeration m-3">
  <h3 class="card-header">Aeration Equation</h3>
  <div class="card-body ">
    <div class="row g-2">
      <div class="col-sm-6 input-double">
        <label for="reaeration_constant">Re-aeration constant</label>
        <div class="input-group">
          <input
            type="text"
            id="reaeration_constant"
            name="reaeration_constant"
            value="{{ defaults.reaeration_constant }}"
            class="no_negs_no_commas_regex form-control"
            required
          />
          <span class="input-group-text units"> - </span>
        </div>
      </div>

      <div class="col-sm-6 input-double">
        <label for="velocity_exponent">Velocity Exponent</label>
        <div class="input-group">
          <input
            type="text"
            id="velocity_exponent"
            name="velocity_exponent"
            value="{{ defaults.velocity_exponent }}"
            class="no_negs_no_commas_regex form-control"
            required
          />
          <span class="input-group-text units"> - </span>
        </div>
      </div>

      <div class="col-sm-6 input-double">
        <label for="depth_exponent">Depth Exponent</label>
        <div class="input-group">
          <input
            type="text"
            id="depth_exponent"
            name="depth_exponent"
            class="form-control"
            value="{{ defaults.depth_exponent }}"
            required
          />
          <span class="input-group-text units"> - </span>
        </div>
      </div>
    </div>
  </div>
</div>

app/templates/includes/_archive-row.html
<div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#Arr{{data['id']}}" aria-expanded="false" aria-controls="flush-collapseOne">

        <!-- Start Accordion Highlight Row -->
        <div class="container">
          <!-- Make styling completely dynamic -->
        <div class="row d-flex justify-content-around">
          <div class="col-md-auto">
            <div class="input-group pb-2">
              <!-- Shorten Unique ID UUID to first 8 digits -->
              <span class="input-group-text" >Unique ID </span>
              <span class="form-control">{{data['id'] | truncate(8, end='')}}</span>
            </div>
          </div>
          <div class="col-md-auto">
            <div class="input-group pb-2">
              <span class="input-group-text" >Name of Simulation </span>
              <span class="form-control">{{data['name_of_simulation']}}</span>
            </div>
          </div>
          <div class="col-md-auto">
            <div class="input-group pb-2">
              <span class="input-group-text" >Username </span>
              <span class="form-control">{{data['username']}}</span>
            </div>
          </div>
          <div class="col-md-auto">
            <div class="input-group pb-2">
              <!-- Edit datetime to human readable format -->
              <span class="input-group-text" >Created at </span>
              <span class="form-control nowrap">{{data['created'].strftime('%H:%M on %d/%m/%Y')}}</span>
            </div>
          </div>
        </div>
      </div>
       <!-- End Accordion Highlight Row -->
      </button>

    </h2>
    <!-- ID must match data-bs-target -->
    <div id="Arr{{data['id']}}" class="accordion-collapse collapse p-3" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
      <!-- Start Accordion Further Information -->
      <div class="container">
        <div class="row d-flex justify-content-around">
          <div class="col-md-auto d-flex flex-column justify-content-center">
            <div class="row pl-5 pr-5 pb-3">
              <div class="input-group">
                <span class="input-group-text" >River Name </span>
                <span class="form-control">
                  <!-- Show only the main part of the the river name, hide part after "-" -->
                  {% set list1 = data['name'].split(' ') %}
                  {% for item in list1 %}
                  {% if item == '-'%}
                  {% break %}
                  {% endif %}
                  {{ item }}
                  {% endfor %} 
                </span>
                </div>
              </div>
              <div class="row pl-5 pr-5 ">
              <div class="input-group">
                <!-- Convert River type to more human readable format -->
                <span class="input-group-text" >River Type </span>
                <span class="form-control">{{data['water_body_type'] | replace("_", ",")}}</span>
                </div>
              </div>
          </div>
          <div class="col-md-auto">
            <!-- START KEY INFO TABLE -->
            <table class="table">
              <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">SOAF Score</th>
                  <th scope="col">WFD Post Spill Standard</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">BOD</th>
                <td class="SOAF{{data['bod_soaf_score']}}">{{data['bod_soaf_score']}}</td>
                <td class="{{data['bod_wfd_standard_post_spill']}}">{{data['bod_wfd_standard_post_spill']}}</td>
              </tr>
              <tr>
                <th scope="row">NH<sub>3</sub></th>
              <td class="SOAF{{data['nh3_soaf_score']}}">{{data['nh3_soaf_score']}}</td>
              <td class="{{data['nh3_wfd_standard_post_spill']}}">{{data['nh3_wfd_standard_post_spill']}}</td>
            </tr>
              </tbody>
            </table>
            <!-- END KEY INFO TABLE -->
          </div>
          <div class="col-md-auto text-center d-flex align-items-center justify-content-center">
            <!-- Automatically generate link to correct outputs page -->
            <a class="btn btn-arup" href="{{ url_for('outputs.outputs_route') }}/{{data['id']}}" role="button">See Full Details</a>
          </div>
        </div>
      </div>
    <!-- End Accordion Further Information -->
  </div>
</div>

app/templates/includes/_basic-naming-card.html
<div class="card m-3" style="z-index: 2000;">
    <h3 class="card-header">Calculation Identification</h3>
    <div class="card-body container text-center" style="position:relative">
    <div class="row align-items-center justify-content-center"> 
        <!-- START SIMULATION NAME -->
        <div class=" col-md-auto col-sm-12">
            <div class="row p-1">
                <div class="col-sm-12 input-group">
                <label for="name_of_sim" class="input-group-text">Simulation Name</label>
                <input
                    type="text"
                    id="name_of_sim"
                    name="name_of_sim"
                    class="form-control"
                    required
                    placeholder="Name Simulation"
                />
                </div>
            </div>
        </div>
            <!-- END SIMULATION NAME -->   
            <!-- START USERNAME -->

        <div class=" col-md-auto col-sm-12">
            <div class="row p-1">
                <div class="col-sm-12 input-group">
                    <label for="username" class="input-group-text">Username</label>
                    <input
                        type="text"
                        id="username"
                        name="username"
                        class="form-control"
                        required
                        placeholder="Enter your username"
                    />
                </div>
            </div>
        </div>
            <!-- END USERNAME -->
            <!-- START RIVER STRETCH NAME -->
        <div class=" col-md-auto col-sm-12">
            <div class="input-group p-2">
                <label for="river_stretch_name" class="input-group-text">Stretch Name</label>
                <input class="form-control" id="river_stretch_name" name="river_stretch_name" type="text"
                    placeholder="Search.." onclick="showRiverStretches()" onfocus="showRiverStretches()"
                    onblur="delayedHideRiverStretches()" autocomplete="off" required >
            </div>
            <div class="filter-list-block" id="stretch_list_container">
                <ul class="list-group" id="river_stretches">
                    {% for river_stretch in river_stretches %}
                    <li class="list-group-item" onclick="populateStretchName(this)">{{ river_stretch }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    <!-- END RIVER STRETCH NAME -->
            
    </div>
</div>
</div>

app/templates/includes/_cso-card.html
<div class="card m-3">
  <h3 class="card-header">CSO Data</h3>
  <div class="card-body container" id="cso_card" style="justify-content: left">

   
    <!-- START CSO CSV INPUT -->
    <!-- HIDDEN ON DEFAULTS PAGE -->
    {% if active_page != 'defaults'%}
    <div class="row g-2 p-3">
      <div class="col-sm-3 d-flex align-items-center justify-content-center">
        <label for="cso_csv">Upload .csv file</label>
      </div>
      <div class="col-sm-9" style="text-align: left">

        <input type="file" id="cso_csv" name="cso_csv" class="form-control" style="text-align: center" accept=".csv"
          required />
      </div>
    </div>

    {% endif %}
    <!-- END CSO CSV INPUT -->
    {% if active_page == 'defaults' %}
    <div class="row g-2">
      <!-- START CSO BOD INPUT -->
        <div class="col-sm-6 input-double">
          <label for="cso_bod_conc_mgl">BOD conc.</label>
          <div class="input-group">
            <input
              type="text"
              id="cso_bod_conc_mgl"
              name="cso_bod_conc_mgl"
              value="{{ defaults.cso_bod_conc_mgl }}"
              class="no_negs_no_commas_regex form-control"
              required
            />
            <span class="input-group-text units"> mg/l </span>
          </div>
        </div>
      <!-- END CSO BOD INPUT -->
  
      <!-- START CSO NH3 INPUT -->
        <div class="col-sm-6 input-double">
          <label for="cso_nh3_conc_mgl">NH<sub>3</sub> conc.</label>
          <div class="input-group">
            <input
              type="text"
              id="cso_nh3_conc_mgl"
              name="cso_nh3_conc_mgl"
              value="{{ defaults.cso_nh3_conc_mgl }}"
              class="no_negs_no_commas_regex form-control"
              required
            />
            <span class="input-group-text units"> mg/l </span>
          </div>
        </div>
       <!-- END CSO NH3 INPUT -->
      </div>
      {% endif %}



  </div>
</div>

app/templates/includes/_cso-inputs.html
<div class="d-flex flex-row"  style="text-align: left;">
	<div class="form-group m-auto p-2 col-sm-1">
		<label class="d-none" for="cso_1">CSO 1</label>
		<div>
			1.
		</div>
	</div>
	<div class="form-group p-2 col-sm-4">
		<label for="cso_id">CSO ID</label>
		<input
			type="text"
			id="cso_id"
			name="cso_id"
			class="form-control"
			required
			placeholder="e.g. usk001"
		/>
	</div>



	<!-- START CSO BOD INPUT -->
		<div class="form-group p-2 col-sm-4">
			<label for="cso_bod_conc_mgl_1">BOD conc.</label>
			<div class="input-group">
				<input
					type="text"
					id="cso_bod_conc_mgl_1"
					name="cso_bod_conc_mgl_1"
					value="{{ defaults.cso_bod_conc_mgl }}"
					class="no_negs_no_commas_regex form-control"
					required
				/>
				<span class="input-group-text units"> mg/l </span>
			</div>
		</div>
	<!-- END CSO BOD INPUT -->

	<!-- START CSO NH3 INPUT -->
		<div class="form-group p-2 col-sm-3">
			<label for="cso_nh3_conc_mgl_1">NH<sub>3</sub> conc.</label>
			<div class="input-group">
				<input
					type="text"
					id="cso_nh3_conc_mgl_1"
					name="cso_nh3_conc_mgl_1"
					value="{{ defaults.cso_nh3_conc_mgl }}"
					class="no_negs_no_commas_regex form-control"
					required
				/>
				<span class="input-group-text units"> mg/l </span>
			</div>
		</div>
	 <!-- END CSO NH3 INPUT -->
</div>

app/templates/includes/_downloads-card.html
<div class="card m-3">
    <h3 class="card-header">Download data</h3>
    <div class="card-body container" style="justify-content: left; ">
        <div class="row align-items-center p-1">
            <div class="input-group">
                <div class="col-sm-9 d-flex">
                    <label for="download-button-inputs">Download input data</label>
                </div>
                <div class="col-sm-3">
                    <button class="btn btn-arup" id="download-button-inputs" onclick="downloadInputs('inputs-' + '{{output_page_values.input_data.archive_id.split('-')[0]}}' + '-' + '{{output_page_values.input_data.sim_datetime}}' + '.csv')">
                        <i class="bi bi-download"></i>
                    </button>
                </div>              
            </div>
        </div>
        <div class="row align-items-center p-1">
            <div class="input-group">
                <div class="col-sm-9 d-flex">
                    <label for="download-button">Download output data</label>
                </div>
                <div class="col-sm-3">
                    <button class="btn btn-arup" id="download-button" onclick="click_download_button('outputs-' + '{{output_page_values.input_data.archive_id.split('-')[0]}}' + '-' + '{{output_page_values.input_data.sim_datetime}}' + '.csv')">
                        <i class="bi bi-download"></i>
                    </button>
                </div>              
            </div>
        </div>
    </div>
</div>

app/templates/includes/_header.html
<div class="container-fluid p-3 river-header text-center">
        <!-- START HEADER STYLING-->
        <h1>River Health Assessor</h1>
        <!-- END HEADER STYLING -->
</div>

app/templates/includes/_help-calculation-and-standards.html
<div class="card m-3">
    <h3 class="card-header">Calculation and Standards</h3>
    <div class="card-body px-5 py-5" id="justify-text">
        <p>When you press the <i>Run Simulation</i> on the application it will take the (log-normal) mean and s.d. of river flow that you have input and convert them to the mean and s.d. of the underlying normal distribution, using the algebra outlined <a href="https://brilliant.org/wiki/log-normal-distribution/#:~:text=The%20mean%20of%20the%20log,m%20%E2%88%92%201%202%20%CF%83%202%20." target="_blank">here</a>.</p>
        <p>The application then uses that normal mean and s.d. to generate a log-normal distribution, and picks a river flow from that distribution.</p>
        <p>The application also picks a random value of BOD and NH<sub>3</sub> concentration, except from a normal distribution generated from their mean and s.d. concentrations.</p>
        <p>These picks are performed for every row of CSO spill data. Each row of spill data therefore gets three values; a river flow, a BOD concentration and an NH<sub>3</sub> concentration.  </p>
        <p>Once the river data has been added to the spill data the calculator performs a mass balance calculation on each row, using the formulas shown below. </p>
        <img src="\static\images\mass_balance_formulas.jpg" class="img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="400" height="500">
        <br>
        <p>The mass-balance calculations result in values for the downstream concentration of BOD and NH3 for each row. This produces a table of results which you can access by clicking <i>Download Output Data</i> on the outputs page. See below for an example of one of these tables. Note that rows where the CSO flow was zero, have been omitted. Also note that the calculator has summed each 5 minute interval of data into hourly intervals of data, where each hourly interval begins on the hour.</p>        
        
        
        <img src="\static\images\mass_balance_output_table.jpg" class="img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="800" height="600">
        <br>
        <p>The calculator then uses this to calculate 99th percentile concentrations of each of the pollutants. This is the concentration of pollutant at which the river is either equal to or below, for 99 percent of the measurements made.</p>
        <p>The 99th percentile is calculated for both the upstream and downstream river i.e. pre-spill and post-spill. This is shown in a box on the outputs page, pictured below.</p>
        <img src="\static\images\pollutant_results_table_example.jpg" class="img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="400" height="200">
        <br>
        <p>As you can see, the river has been given a Water Framework Directive score both before and after the spill. This is based on tables 5.4(c) and 5.4(d) of the WFD framework found <a href="https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/307788/river-basin-planning-standards.pdf" target="_blank">here</a> and pictured below.</p>
        <img src="\static\images\wfd_standards_tables.jpg" class="img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="700" height="800">
        <br>
        <p>If any of the values change in the framework, you can navigate to the <a href="/standards">standards page</a> and update them in the application.</p>
        <p>Just below the WFD standards, the in-class deterioration is shown. This is used to calculate the Storm Overflow Assessment Framework (SOAF) impact score, based on table 7 of the SOAF <a href="https://www.water.org.uk/wp-content/uploads/2018/12/SOAF.pdf">guide</a>, which is pictured below. </p>
        <img src="\static\images\soaf_impact_score_table.jpg" class="img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="600" height="400">
        <br>
        <p>Finally, the impact classification is shown, which is based on table 11 of the SOAF guide, pictured below.</p>
        <img src="\static\images\soaf_impact_classification.jpg" class="img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="600" height="400">
        <br>
        <p>If you would like to improve the accuracy of the modelling of the river, you can increase the <i>number of simulations</i>. This means that the above process of finding the 99th percentile is repeated the number of times you specify in the number of simulations field and the results are averaged, as is commonly done in <a href="https://en.wikipedia.org/wiki/Monte_Carlo_method" target="_blank">Monte Carlo</a> simulations.</p>
        <p>Note that while increasing the number of simulations does improve the accuracy of the model, results tend to converge at about 10 simulations.</p>
        </div>
</div>

app/templates/includes/_help-upstream-data.html
<div class="card m-3">
    <h3 class="card-header">Upstream Data</h3>
    <div class="card-body px-5 py-5" id="justify-text">
            <!-- The following attributes are needed to make images responsive: class="img-fluid"and alt="Responsive image -->
            <h5>River Flow</h5>
            <p >There are four different ways to add (log-normally distributed) river flow data.</p>
            <p>1. The first is to input the river flow mean and s.d. manually.</p>
            <p>2. Alternatively, you can add river flow data by using the application Qube. In Qube, export a .csv file where the format of the time and the units of flow are the same as in the image below.</p>
            <img src="\static\images\qube_example.jpg" class="m-2 img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="260" height="210">
            <p>3. You can also add river flow by selecting a river station from the NRFA dropdown. This will populate the flow field with data from the last ten years. If there is no data for that station in the last ten years, an alert will be shown and the flow field will not be populated.</p>  
            <img src="\static\images\nrfa_dropdown.jpg" class="m-2 img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="390" height="130">
            <p>4. Finally, you have the option of using the results of a previous calculation i.e. its downstream values of flow and pollutants, to become the upstream values of a new calculation.</p>
            <img src="\static\images\previous_calc_input_example.jpg" class="m-2 img-fluid img-thumbnail rounded mx-auto d-block" alt="Responsive image" width="450" height="170">
            <br>
            <h5>Pollutant Concentrations</h5>
            <p>As stated, when inputting the river flow mean and s.d., these must be in log-normal form. However, when inputting the BOD and NH<sub>3</sub> concentration mean and s.d., these must be of their normal distribution.</p>
        </div>
</div>

app/templates/includes/_nrfa-scrape.html
<div class="card m-3">
    <h3 class="card-header">NRFA API</h3>
    <div class="card-body">
        <div class="row g-2 p-2 fs-5" id="justify-text">
            <p>The button below will go to the NRFA API and if it finds any new river stations, it will add those stations to the system. </p>
            <p>This may take a few seconds, please wait for an alert to display on this page that it is complete.</p>
        </div>
        <div class="row g-2 p-2 justify-content-center">
            <div class="col-sm-auto">
                <button class="btn btn-arup" onclick="scrapeNRFA()">Update NRFA Stations</button>
            </div>
        </div>
    </div>
  </div>

app/templates/includes/_river-flow-bod-nh3-card.html
<div class="card m-3">
    <h3 class="card-header">Basic River Parameters</h3>
    <div class="card-body container text-center" style="position:relative">
    
    <!-- START FLOW RATE INPUTS -->
    <!-- HIDDEN ON DEFAULTS PAGE -->
    {% if active_page != 'defaults'%}
        <div class="input-mean-sd mb-0">
            <label>Flow Rate</label>
            <div class="input-group">
                <label for="river_flow_ls" class="input-group-text" id="basic-addon3">Mean</label>
                <input type="text" id="river_flow_ls" name="river_flow_ls" class="no_negs_no_commas_regex form-control"
                    required />
                <label for="river_flow_ls_sd" class="input-group-text">SD</label>
                <input type="text" id="river_flow_ls_sd" name="river_flow_ls_sd"
                    class="no_negs_no_commas_regex form-control" required aria-describedby="autopopulated_from_flow"/></label>
                <span class="input-group-text units">l/s</span>
            </div>
        </div>
        <small id="autopopulated_from_flow" class="form-text text-muted invisible">Flow rate autopopulated from a previous simulation</small>
    {% endif %}
    <!-- END FLOW RATE INPUTS -->
    
    <!-- START BOD INPUTS -->
        <div class="input-mean-sd mb-0">
            <label>BOD conc. </label>
            <div class="input-group">
                <label for="river_bod_mgl" class="input-group-text">Mean</label>
                <input type="text" id="river_bod_mgl" name="river_bod_mgl" value="{{ defaults.river_bod_mgl }}"
                    class="no_negs_no_commas_regex form-control" required />
                <label for="river_bod_mgl_sd" class="input-group-text">SD</label>
                <input type="text" id="river_bod_mgl_sd" name="river_bod_mgl_sd"
                    value="{{ defaults.river_bod_mgl_sd }}" class="no_negs_no_commas_regex form-control" required />
                <span class="input-group-text units">mg/l</span>
            </div>
        </div>
        <small id="autopopulated_from_bod" class="form-text text-muted invisible">BOD values autopopulated from a previous simulation</small>
    <!-- END BOD INPUTS -->

    <!-- START NH3 INPUTS -->
        <div class="input-mean-sd mb-0">
            <label>NH<sub>3</sub> conc. </label>
            <div class="input-group">
                <label for="river_nh3_mgl" class="input-group-text">Mean</label>
                <input type="text" id="river_nh3_mgl" name="river_nh3_mgl" value="{{ defaults.river_nh3_mgl }}"
                    class="no_negs_no_commas_regex form-control" required />
                <label for="river_nh3_mgl_sd" class="input-group-text">SD</label>
                <input type="text" id="river_nh3_mgl_sd" name="river_nh3_mgl_sd"
                    value="{{ defaults.river_nh3_mgl_sd }}" class="no_negs_no_commas_regex form-control" required />
                <span class="input-group-text units">mg/l</span>
            </div>
        </div>
        <small id="autopopulated_from_nh3" class="form-text text-muted invisible"">Ammonia values autopopulated from a previous simulation</small>
    <!-- END NH3 INPUTS -->
    </div>
</div>

app/templates/includes/_river-params-card.html
<div class="card params m-3">
  <h3 class="card-header">River Parameters</h3>
  <div class="card-body">
    <div class="row g-2">
      <div class="col-sm-6 input-double">
        <label for="river_mannings_no">Manning's No.</label>
        <div class="input-group">
          <input
            type="text"
            id="river_mannings_no"
            name="river_mannings_no"
            value="{{ defaults.river_mannings_no }}"
            class="no_negs_no_commas_regex form-control"
            required
          />
          <span class="input-group-text units"> - </span>
        </div>
      </div>

      <div class="col-sm-6 input-double">
        <label for="river_bod_decay_rate_day">BOD Decay Rate</label>
        <div class="input-group">
          <input
            type="text"
            id="river_bod_decay_rate_day"
            name="river_bod_decay_rate_day"
            value="{{ defaults.river_bod_decay_rate_day }}"
            class="no_negs_no_commas_regex form-control"
            required
          />
          <span class="input-group-text units"> l/day </span>
        </div>
      </div>

      <div class="col-sm-6 input-double">
        <label for="river_nh3_decay_rate_day">NH<sub>3</sub> Decay Rate</label>
        <div class="input-group">
          <input
            type="text"
            id="river_nh3_decay_rate_day"
            name="river_nh3_decay_rate_day"
            value="{{ defaults.river_nh3_decay_rate_day }}"
            class="no_negs_no_commas_regex form-control"
            required
          />
          <span class="input-group-text units"> l/day </span>
        </div>
      </div>

      <div class="col-sm-6 input-double">
        <label for="river_nh3_yield_factor_gN_gO2"
          >NH<sub>3</sub> Yield Factor
        </label>
        <div class="input-group">
          <input
            type="text"
            id="river_nh3_yield_factor_gN_gO2"
            name="river_nh3_yield_factor_gN_gO2"
            value="{{ defaults.river_nh3_yield_factor_gN_gO2 }}"
            class="no_negs_no_commas_regex form-control"
            required
          />
          <span class="input-group-text units"> gO<sub>2</sub>/gN </span>
        </div>
      </div>

      <div class="col-sm-6 input-double">
        <label for="river_nh3_gain_bod_gN_gO2"
          >NH<sub>3</sub> Gain from BOD decay
        </label>
        <div class="input-group">
          <input
            type="text"
            id="river_nh3_gain_bod_gN_gO2"
            name="river_nh3_gain_bod_gN_gO2"
            value="{{ defaults.river_nh3_gain_bod_gN_gO2 }}"
            class="no_negs_no_commas_regex form-control"
            required
          />
          <span class="input-group-text units"> gN/gO<sub>2</sub> </span>
        </div>
      </div>
    </div>
  </div>
</div>